services:
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - try_next_server_components

  frontend:
    image: node:22
    container_name: frontend
    expose:
      - 8080
    volumes:
      - type: bind
        source: ./front
        target: /app
    tty: true
    networks:
      - try_next_server_components

  backend:
    image: golang:1.23.4
    container_name: backend
    expose:
      - 8080
    volumes:
      - type: bind
        source: ./server
        target: /go/src
    tty: true
    networks:
      - try_next_server_components

networks:
  try_next_server_components:
    driver: bridge